# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_PAT }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Setup registry
        run: |
          pnpm set @1stcathays:registry=https://npm.pkg.github.com/1stcathays
          pnpm set "//npm.pkg.github.com/:_authToken=${{ secrets.CI_PAT }}"

      - name: Version and publish
        env:
          GH_TOKEN: ${{ secrets.CI_PAT }}
        run: |
          git config user.name "1stcathays-bot"
          git config user.email "1stcathays-bot@users.noreply.github.com"

          pnpm release
